# Generated by Django 4.0.5 on 2024-07-07 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Retrovizori', 'Retrovizori'), ('Farovi', 'Farovi'), ('Stopke', 'Stopke'), ('Gabariti', 'Gabariti'), ('Masine za injektore', 'Masine za injektore'), ('Sijalice', 'Sijalice'), ('Semerinzi', 'Semerinzi'), ('Zracni jastuci', 'Zracni jastuci'), ('Kocioni sistemi', 'Kocioni sistemi'), ('Dizel program', 'Dizel program'), ('Zracni ventili i reparacije', 'Zracni ventili i reparacije'), ('Crijeva za vodu', 'Crijeva za vodu'), ('Karoserija', 'Karoserija'), ('Hidraulika', 'Hidraulika'), ('Kompresori zraka', 'Kompresori zraka'), ('Grijanje i hladjenje', 'Grijanje i hladjenje'), ('Filteri', 'Filteri'), ('Ulje i maziva', 'Ulje i maziva'), ('Setovi kvacila', 'Setovi kvacila'), ('Dijelovi diferencijala i reduktora', 'Dijelovi diferencijala i reduktora'), ('Spojnice i prikljucci', 'Spojnice i prikljucci')], default='Farovi', max_length=125)),
                ('image', models.ImageField(upload_to='')),
                ('o', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
