# Generated by Django 4.0.5 on 2024-07-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(default='123', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='oem',
            field=models.CharField(default='123', max_length=50),
        ),
    ]
